### ISSUE TITLE
How to Access Lock Pick Strength Config Option?

### ISSUE THREAD

**Issue by dirt-worm** [Melonslise/Locks#48]
I might just be dumb but I cannot find the lock pick strength config option in either the common or client config files. In the feature showcase video, the mod-maker accessed this option through a "Mod Options" button in the game menu, but I don't seem to have that option on my game.

For some reason my lock picks are very weak by default and break many times before i can even open one lock! Any help with this would be greatly appreciated :^)

**Comment by MercurialPony** [comment]
That's a pretty old video I made in 1.12. Since then forge doesn't provide a Mod Options button so you have to go into your save directory and edit the locks-server.cfg file. You should also know that since the last update there's another way to do this: you can change the nbt of an individual lock pick by doing something like /give locks:lock_pick{Strength:x}, where x is your desired strength
